normal_config:
  algo_denoise_config:
    no_face_scene:
      traditional_mfnr_strength:
        # nr_strength range[0,8] motion_ratio range[1.0, +]
        iso0: [1.0,  1.2,  2.85, 1.0]
        iso1: [1.8,  2.2,  3.83, 1.0]
        iso2: [3.8,  4.2,  7.94, 1.0]
        iso3: [7.8,  8.2,  7.94, 1.0]
        iso4: [15.8,16.2,  7.94, 1.0]
        iso5: [31.9,  45,  7.94, 1.0]
        iso6: [60,    70,  7.94, 1.0]
        iso7: [120,  140,  7.94, 1.0]
        iso8: [200,  256,  7.94, 1.0]
      detail_addback_weight:
        # weight range[0,1]
        iso0: [1.0,  1.2,  64,  128,  0.18,  0.30,  1.0,  1.0,  1.0,  1.0] 
        iso1: [1.8,  2.2,  64,  128,  0.18,  0.30,  1.0,  1.0,  1.0,  1.0]   
        iso2: [3.8,  4.2,  64,  78,  0.18,  0.27,  1.0,  0.9,  0.8,  0.8]   
        iso3: [7.8,  8.2,  64,  84,  0.18,  0.23,  1.0,  0.9,  0.8,  0.8]  
        iso4: [15.8,16.2,  64,  92,  0.15,  0.13,  1.0,  0.9,  0.8,  0.8]   
        iso5: [31.9,  45,  64,  104,  0.13,  0.13,  1.0,  0.9,  0.8,  0.8]    
        iso6: [60,    70,  64,  128,  0.10,  0.10,  1.0,  1.0,  1.0,  1.0]   
        iso7: [120,  140,  64,  128,  0.10,  0.10,  1.0,  1.0,  1.0,  1.0]   
        iso8: [200,  256,  64,  128,  0.10,  0.10,  1.0,  1.0,  1.0,  1.0]
      
    face_scene:
      traditional_mfnr_strength:
        # nr_strength range[0,8] motion_ratio range[1.0, +]
        iso0: [1.0,  1.2,  1.45, 1.0]
        iso1: [1.8,  2.2,  1.83, 1.0]
        iso2: [3.8,  4.2,  2.94, 1.0]
        iso3: [7.8,  8.2,  2.94, 1.0]
        iso4: [15.8,16.2,  2.94, 1.0]
        iso5: [31.9,  45,  2.94, 1.0]
        iso6: [60,    70,  2.94, 1.0]
        iso7: [120,  140,  2.94, 1.0]
        iso8: [200,  256,  2.94, 1.0]
      detail_addback_weight:
        # weight range[0,1]
        iso0: [1.0,  1.2,  64,  78,  0.16,  0.23,  1.0,  1.0,  1.0,  1.0] 
        iso1: [1.8,  2.2,  64,  78,  0.16,  0.23,  1.0,  1.0,  1.0,  1.0]   
        iso2: [3.8,  4.2,  64,  78,  0.16,  0.23,  1.0,  1.0,  0.9,  0.8]   
        iso3: [7.8,  8.2,  64,  84,  0.14,  0.20,  1.0,  1.0,  0.9,  0.8]  
        iso4: [15.8,16.2,  64,  84,  0.13,  0.18,  1.0,  1.0,  0.9,  0.8]   
        iso5: [31.9,  45,  64,  84,  0.12,  0.16,  1.0,  1.0,  0.9,  0.8]    
        iso6: [60,    70,  64,  128,  0.10,  0.15,  1.0,  1.0,  1.0,  1.0]   
        iso7: [120,  140,  64,  128,  0.10,  0.15,  1.0,  1.0,  1.0,  1.0]   
        iso8: [200,  256,  64,  128,  0.10,  0.15,  1.0,  1.0,  1.0,  1.0]
  
    dump_luma_weight_map: false
    dump_motion_weight_map: false

  algo_sharpen_config:
    g_sharpen:
      enabled: true
      ishalocontrol: true
      islocaloshoot: true
      islocalushoot: true
      E_str_min: 1.0
      E_str_max: 64.0
      T_str_min: 0.0
      T_str_max: 256.0
      ct_thre: 4.0
      delta_min: 0.5
      e_wgt: 
      [1.0,  1.0,  1.0,  1.0,
      1.0,  1.0,  1.0,  1.0,
      1.0,  1.0,  1.0,  1.0,
      1.0,  1.0,  1.0,  1.0,
      0.92, 0.84, 0.76, 0.68, 
      0.6,  0.52, 0.44, 0.36, 
      0.28, 0.2,  0.12, 0.1, 
      0.1,  0.1,  0.1,  0.1]
      t_wgt: 
      [0.0,  0.0,  0.07, 0.2,
      0.4,  0.6,  0.8,  1.0, 
      1.0,  1.0,  1.0,  1.0, 
      1.0,  1.0,  1.0,  1.0, 
      1.0,  1.0,  1.0,  1.0, 
      1.0,  1.0,  1.0,  1.0, 
      1.0,  1.0,  1.0,  1.0, 
      1.0,  1.0,  1.0,  1.0]
      amount_edge: 0.5
      amount_detail: 0.5
      E_control_min: 0.1
      oshoot: 0.4
      ushoot: 0.8
      portrait_wgt: 0.0
      radial_anchor: [1.0, 1.0, 1.0, 1.0, 1.0]
  
lowlight_config:
