normal_config:
  algo_denoise_config:
    no_face_scene:
      traditional_mfnr_strength:
        # nr_strength range[0,8] motion_ratio range[1.0, +]
        iso0: [1.0,  1.2,  0.45, 1.0]
        iso1: [1.8,  2.2,  0.83, 1.0]
        iso2: [3.8,  4.2,  1.54, 1.0]
      detail_addback_weight:
        # weight range[0,1]
        iso0: [1.0,  1.2,  64,  128,  0.30,  0.30,  1.0,  1.0,  1.0,  1.0] 
        iso1: [1.8,  2.2,  64,  128,  0.28,  0.28,  1.0,  1.0,  1.0,  1.0] 
        iso2: [3.8,  4.2,  64,  128,  0.30,  0.30,  1.0,  1.0,  1.0,  1.0] 
        iso3: [7.6,  8.4,  64,  128,  0.30,  0.30,  1.0,  1.0,  1.0,  1.0] 
        iso4: [15,    17,  64,  128,  0.24,  0.24,  1.0,  1.0,  1.0,  1.0]  
        iso5: [28,    36,  64,  128,  0.20,  0.20,  1.0,  1.0,  1.0,  1.0]   
        iso6: [58,    70,  64,  128,  0.15,  0.15,  1.0,  1.0,  1.0,  1.0]  
        iso7: [112,  144,  64,  128,  0.15,  0.15,  1.0,  1.0,  1.0,  1.0]  
        iso8: [224,  256,  64,  128,  0.15,  0.15,  1.0,  1.0,  1.0,  1.0]
    
    face_scene:
      traditional_mfnr_strength:
        # nr_strength range[0,8] motion_ratio range[1.0, +]
        iso0: [1.0,  1.2,  0.45, 1.0]
        iso1: [1.8,  2.2,  0.83, 1.0]
        iso2: [3.8,  4.2,  1.54, 1.0]
      detail_addback_weight:
        # weight range[0,1]
        iso0: [1.0,  1.2,  64,  128,  0.30,  0.30,  1.0,  1.0,  1.0,  1.0] 
        iso1: [1.8,  2.2,  64,  128,  0.28,  0.28,  1.0,  1.0,  1.0,  1.0] 
        iso2: [3.8,  4.2,  64,  128,  0.30,  0.30,  1.0,  1.0,  1.0,  1.0] 
        iso3: [7.6,  8.4,  64,  128,  0.30,  0.30,  1.0,  1.0,  1.0,  1.0] 
        iso4: [15,    17,  64,  128,  0.24,  0.24,  1.0,  1.0,  1.0,  1.0]  
        iso5: [28,    36,  64,  128,  0.20,  0.20,  1.0,  1.0,  1.0,  1.0]   
        iso6: [58,    70,  64,  128,  0.15,  0.15,  1.0,  1.0,  1.0,  1.0]  
        iso7: [112,  144,  64,  128,  0.15,  0.15,  1.0,  1.0,  1.0,  1.0]  
        iso8: [224,  256,  64,  128,  0.15,  0.15,  1.0,  1.0,  1.0,  1.0] 
    
    dump_luma_weight_map: false
    dump_motion_weight_map: false
    
  algo_sharpen_config:
    g_sharpen:
      enabled: true
      ishalocontrol: true
      islocaloshoot: true
      islocalushoot: true
      E_str_min: 1.0
      E_str_max: 64.0
      T_str_min: 0.0
      T_str_max: 256.0
      ct_thre: 4.0
      delta_min: 0.5
      e_wgt: 
      [1.0,  1.0,  1.0,  1.0,
      1.0,  1.0,  1.0,  1.0,
      1.0,  1.0,  1.0,  1.0,
      1.0,  1.0,  1.0,  1.0,
      0.92, 0.84, 0.76, 0.68, 
      0.6,  0.52, 0.44, 0.36, 
      0.28, 0.2,  0.12, 0.1, 
      0.1,  0.1,  0.1,  0.1]
      t_wgt: 
      [0.0,  0.0,  0.07, 0.2,
      0.4,  0.6,  0.8,  1.0, 
      1.0,  1.0,  1.0,  1.0, 
      1.0,  1.0,  1.0,  1.0, 
      1.0,  1.0,  1.0,  1.0, 
      1.0,  1.0,  1.0,  1.0, 
      1.0,  1.0,  1.0,  1.0, 
      1.0,  1.0,  1.0,  1.0]
      amount_edge: 1.0
      amount_detail: 1.0
      E_control_min: 0.1
      oshoot: 0.8
      ushoot: 0.8
      portrait_wgt: 0.0
      radial_anchor: [1.0, 1.0, 1.0, 1.0, 1.0]
  
lowlight_config:

